Summary: added help output

diff --git a/bin/jube-autorun b/bin/jube-autorun
--- a/bin/jube-autorun
+++ b/bin/jube-autorun
@@ -18,16 +18,6 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-# This script allows automated full benchmark execution
-# Options:
-#   -r: additional run args
-#   -c: additional continue args
-#   -a: additional analyse args
-#   -s: additional result args
-#   -p: progress check interval in seconds (default:30)
-#   -o: only show result output
-# Usage: jube-autorun [OPTIONS] input_file.xml
-
 OUTPUT_FILE=jube_job_output.txt
 ONLY_RESULT_OUTPUT=0
 PROGRESS_INTERVAL=30
@@ -38,26 +28,44 @@ then
   rm $OUTPUT_FILE
 fi
 
+function print_usage () {
+    echo "usage: ${0##*/} [OPTIONS] BENCHMARK_CONFIG_FILE"
+    echo "This script automates full benchmark execution, including"
+    echo "steps the run asynchronously, e.g. in a batch system."
+    echo ""
+    echo "Options:"
+    echo "  -r ARG   additional run args"
+    echo "  -c ARG   additional continue args"
+    echo "  -a ARG   additional analyse args"
+    echo "  -s ARG   additional result args"
+    echo "  -p ARG   progress check interval in seconds (default:30)"
+    echo "  -o       only show result output"
+    echo "Example: ${0##*/} input_file.xml"
+}
+
 # Parse optional arguments
-while getopts r:c:a:s:p:o opt
-do
-	case $opt in
-        r) RUN_ARG=$OPTARG;;
-        c) CONTINUE_ARG=$OPTARG;;
-        a) ANALYSE_ARG=$OPTARG;;
-        s) RESULT_ARG=$OPTARG;;
-        p) PROGRESS_INTERVAL=$OPTARG;;
+while getopts r:c:a:s:p:o OPT; do
+    case $OPT in
+        r) RUN_ARG="$OPTARG";;
+        c) CONTINUE_ARG="$OPTARG";;
+        a) ANALYSE_ARG="$OPTARG";;
+        s) RESULT_ARG="$OPTARG";;
+        p) PROGRESS_INTERVAL="$OPTARG";;
         o) ONLY_RESULT_OUTPUT=1;;
-        ?) exit 1;;
+        *)
+            print_usage
+            exit 2
     esac
 done
-shift $((OPTIND-1))
+shift $(( OPTIND - 1 ))
+OPTIND=1
 
 # check if input file exists
 if [ $# -lt 1 ]
 then
-	echo "$0: ERROR (MISSING ARGUMENT, PLEASE ATTACH BENCHMARK CONFIG FILE)"
-	exit 1
+    echo "$0: missing argument"
+    print_usage
+    exit 1
 fi
 
 # start benchmark execution
